uploads = []
generated = []

[[outputs]]
id = "2JDhtgNG8ksTqnziUT5lL"
uri = "file://attached_assets/hostgator-php/shopos-storage.php.txt"
type = "text"
title = "shopos-storage.php (rename to .php after download)"

[[outputs]]
id = "btXrQUBDgnW-FvyDJUhKE"
uri = "file://attached_assets/hostgator-php/shopos-storage.tar.gz"
type = "unspecified"
title = "shopos-storage.tar.gz (alternative archive)"
